### ISSUE TITLE
[Feature request] How to animation gmap customer marker

### ISSUE THREAD

**Issue by thanhchuongbmd** [eregnier/vue2-gmap-custom-marker#51] opened 2021-02-26 09:20 UTC
I think this is mistake, can not animation marker. I am using marker to tracking car on map. Please add this feature

**Comment by eregnier** [comment] 2021-02-27 15:48
Hey, you can just use a gif image or do some css to animate markers. Look at the [demo](https://vue2-gmap-custom-marker-demo.pages.dev/) to have an exemple of what is doable.

As it is possible to animate markers i close this issue. However if the issue is something i missed in you explaination, feel free to reopen.

**Comment by thanhchuongbmd** [comment] 2021-03-06 02:30
> Hey, you can just use a gif image or do some css to animate markers. Look at the [demo](https://vue2-gmap-custom-marker-demo.pages.dev/) to have an exemple of what is doable.
> 
> As it is possible to animate markers i close this issue. However if the issue is something i missed in you explaination, feel free to reopen.

Yes, this marker can animate with style css, but then I zoom map or drag map is it working incorrect!
![ezgif com-gif-maker](https://user-images.githubusercontent.com/67777599/110192077-8f3b8400-7e5e-11eb-904e-0452079bb5a4.gif)

**Comment by thanhchuongbmd** [comment] 2021-03-06 02:44
When I using mixed with package "marker-animate-unobtrusive" then it working ok
Refer link: https://stackoverflow.com/questions/55716325/initializing-marker-animate-unobtrusive-in-vue-fails

**Comment by eregnier** [comment] 2021-03-06 17:14
Your issue seems / looks like to be marker coordinates that are not constant. If you want to animate the marker, set it's coordonates and ensure they are constant over time then only you can add a css animation layer that animate the marker around it's fixed coordonates location.

**Comment by thanhchuongbmd** [comment] 2021-03-08 01:56
> Your issue seems / looks like to be marker coordinates that are not constant. If you want to animate the marker, set it's coordonates and ensure they are constant over time then only you can add a css animation layer that animate the marker around it's fixed coordonates location.

Those marker coordinates can not be constant, because It allways moving realtime. How to animate when change coordinate those markers

**Comment by eregnier** [comment] 2021-12-22 11:41
Hey @thanhchuongbmd sorry for the delay, I did not saw your reply and maybe I closed the issue to quickly.

Do you still have the issue ?

Having a look (for the first time just now :disappointed: ) I think there is an issue with your coordonate computation so the marker jumps. Maybe something does not work as expected on this plugin side, but I have no exemple available to test something like your application. I might help you solve this If you still have troubles with this. If you solved this and want to share the resolution, feel free to do it here.

Sorry again to have closed this issue too quickly

**Comment by goela268** [comment] 2022-01-14 09:06
> Look at the [demo](https://vue2-gmap-custom-marker-demo.utopland.net/) to have an exemple of what is doable.


Hey there, I just wanted to sneak in, to tell you the demo is down. Is this project still maintained? Thank you for your work!

**Comment by eregnier** [comment] 2022-02-01 08:57
This project is not dead at all ! the demo just moved here https://vue2-gmap-custom-marker-demo.pages.dev/ 
where did you get the link ? the link on the project homepage is up to date. I should alias the old demo url to the new demo url I guess :smile:

**Comment by eregnier** [comment] 2022-09-14 13:43
inactivity

**Closed as completed by eregnier** 2022-09-14 13:43 UTC
